export const SHOW_MODAL = "SHOW_MODAL";

//* Get All
export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const GET_DEPARTMENTS = "GET_DEPARTMENTS";
export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const GET_TICKETS = "GET_TICKETS";

//* Get by ID
export const GET_CUSTOMERSBYID = "GET_CUSTOMERSBYID";
export const EMPLOYEE_BY_ID = "EMPLOYEE_BY_ID";
export const GET_TICKETBYID = "GET_TICKETBYID";

//*  Loaders
export const LOGIN_LOADER = "LOGIN_LOADER";
export const CUSTOMERS_LOADER = "CUSTOMERS_LOADER";
export const DEPARTMENT_LOADER = "DEPARTMENT_LOADER";
export const EMPLOYEES_LOADER = "EMPLOYEES_LOADER";
export const TICKET_LOADER = "TICKET_LOADER";

export const EMPLOYEE_BY_ID_LOADER = "EMPLOYEE_BY_ID_LOADER";
export const TICKET_BY_ID_LOADER = "TICKET_BY_ID_LOADER";
export const CUSTOMERSBYID_LOADER = "CUSTOMERSBYID_LOADER";
